<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\YourCityModule\Event;

use MU\YourCityModule\Event\Base\AbstractFilterServiceOfLocationEvent;

/**
 * Event implementation class for filtering service of location processing.
 */
class FilterServiceOfLocationEvent extends AbstractFilterServiceOfLocationEvent
{
    // feel free to extend the event class here
}
