<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\YourCityModule\Form\DataTransformer;

use MU\YourCityModule\Form\DataTransformer\Base\AbstractUploadFileTransformer;

/**
 * Upload file transformer implementation class.
 *
 * This data transformer treats uploaded files.
 */
class UploadFileTransformer extends AbstractUploadFileTransformer
{
    // feel free to add your customisation here
}
