<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\YourCityModule\Form\Type;

use MU\YourCityModule\Form\Type\Base\AbstractBranchType;

/**
 * Branch editing form type implementation class.
 */
class BranchType extends AbstractBranchType
{
    // feel free to extend the branch editing form type class here
}
