<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\YourCityModule\Form\Type;

use MU\YourCityModule\Form\Type\Base\AbstractSpecialOfLocationType;

/**
 * Special of location editing form type implementation class.
 */
class SpecialOfLocationType extends AbstractSpecialOfLocationType
{
    // feel free to extend the special of location editing form type class here
}
