<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\YourCityModule;

use MU\YourCityModule\Base\AbstractYourCityModuleInstaller;

/**
 * Installer implementation class.
 */
class YourCityModuleInstaller extends AbstractYourCityModuleInstaller
{
    // feel free to extend the installer here
}
