<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\YourCityModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\YourCityModule\Entity\LocationEntity;

/**
 * Event base class for filtering location processing.
 */
class AbstractFilterLocationEvent extends Event
{
    /**
     * @var LocationEntity Reference to treated entity instance.
     */
    protected $location;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterLocationEvent constructor.
     *
     * @param LocationEntity $location Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(LocationEntity $location, $entityChangeSet = [])
    {
        $this->location = $location;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return LocationEntity
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
