<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\YourCityModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use MU\YourCityModule\Entity\SpecialOfLocationEntity;

/**
 * Event base class for filtering special of location processing.
 */
class AbstractFilterSpecialOfLocationEvent extends Event
{
    /**
     * @var SpecialOfLocationEntity Reference to treated entity instance.
     */
    protected $specialOfLocation;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterSpecialOfLocationEvent constructor.
     *
     * @param SpecialOfLocationEntity $specialOfLocation Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(SpecialOfLocationEntity $specialOfLocation, $entityChangeSet = [])
    {
        $this->specialOfLocation = $specialOfLocation;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return SpecialOfLocationEntity
     */
    public function getSpecialOfLocation()
    {
        return $this->specialOfLocation;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
