services:
    # Entity factory
    mu_yourcity_module.entity_factory:
        class: MU\YourCityModule\Entity\Factory\EntityFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@mu_yourcity_module.entity_initialiser"
            - "@mu_yourcity_module.collection_filter_helper"
            - "@mu_yourcity_module.feature_activation_helper"
    
    # Entity initialiser
    mu_yourcity_module.entity_initialiser:
        class: MU\YourCityModule\Entity\Factory\EntityInitialiser
        arguments:
        - "@mu_yourcity_module.listentries_helper"
        - "@=service('zikula_extensions_module.api.variable').get('MUYourCityModule', 'defaultLatitude', 0.00)"
        - "@=service('zikula_extensions_module.api.variable').get('MUYourCityModule', 'defaultLongitude', 0.00)"
        - "@=service('zikula_extensions_module.api.variable').get('MUYourCityModule', 'city', '')" 
        - "@=service('zikula_extensions_module.api.variable').get('MUYourCityModule', 'areaCode', '')"
        - "@=service('zikula_extensions_module.api.variable').get('MUYourCityModule', 'standardZipCode', '')"       
