services:
    # Form field types
    
    mu_yourcity_module.form.type.field.geo:
        class: MU\YourCityModule\Form\Type\Field\GeoType
        tags:
            - { name: form.type }
    
    mu_yourcity_module.form.type.field.multilist:
        class: MU\YourCityModule\Form\Type\Field\MultiListType
        arguments:
            - "@mu_yourcity_module.listentries_helper"
        tags:
            - { name: form.type }
    
    mu_yourcity_module.form.type.field.translation:
        class: MU\YourCityModule\Form\Type\Field\TranslationType
        tags:
            - { name: form.type }
    
    mu_yourcity_module.form.type.field.upload:
        class: MU\YourCityModule\Form\Type\Field\UploadType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_yourcity_module.image_helper"
            - "@mu_yourcity_module.upload_helper"
        tags:
            - { name: form.type }
    
    mu_yourcity_module.form.type.field.user:
        class: MU\YourCityModule\Form\Type\Field\UserType
        arguments:
            - "@zikula_users_module.user_repository"
        tags:
            - { name: form.type }
