<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\YourCityModule\Form\Type\Field;

use MU\YourCityModule\Form\Type\Field\Base\AbstractColourType;

/**
 * Colour field type implementation class.
 *
 * The allowed formats are '#RRGGBB' and '#RGB'.
 */
class ColourType extends AbstractColourType
{
    // feel free to add your customisation here
}
