<?php
/**
 * YourCity.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\YourCityModule\Entity\Repository;

use MU\YourCityModule\Entity\Repository\Base\AbstractServiceOfLocationTranslationRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for service of location translation entities.
 */
class ServiceOfLocationTranslationRepository extends AbstractServiceOfLocationTranslationRepository
{
    // feel free to add your own methods here
}
